Feature 5 vehicle list screen
Metatavu/vp-kuljetus-transport-management pull request #13
Opened 2024-02-09 15:58 UTC by EVP1989

Resolves #5

2024-02-16 13:47 UTC, lauriLukkarinen requested changes

2024-02-16 13:47 UTC, lauriLukkarinen commented on src/components/vehicle-list-screen.tsx
> +        },
```suggestion
        renderHeader: params => (
          <Stack direction="row">
            <Typography fontWeight={"bold"} fontSize={14}>{params.colDef.headerName}</Typography>
          </Stack>
        ),
```

2024-02-16 13:47 UTC, lauriLukkarinen commented on src/components/vehicle-list-screen.tsx
> +  };
```suggestion
  const buildRow = (truck: Truck) => {
    return {
      id: truck.id,
      name: truck.plateNumber,
      number: truck.vin,
      address: "-",
      location: "-",
      status: "-",
      trailer: "-",
      driver: "-"
    } as const;
  };
```

2024-02-16 13:47 UTC, lauriLukkarinen commented on src/components/vehicle-list-screen.tsx
> +      const trucks: Truck[] = await trucksApi.listTrucks({});
```suggestion
      const trucks = await trucksApi.listTrucks({});
```

2024-02-16 13:47 UTC, lauriLukkarinen commented on src/components/vehicle-list-screen.tsx
> +      const vehicleRows = trucks.map((truck) => buildRow(truck));
```suggestion
      const vehicleRows = trucks.map(buildRow);
```

2024-02-16 13:47 UTC, lauriLukkarinen commented on src/localization/locales/fi.json
> +    "vehicleListing": "Ajoneuvolistaukssessa tapahtui virhe"
```suggestion
    "vehicleListing": "Ajoneuvolistauksessa tapahtui virhe"
```

2024-02-18 15:03 UTC, EVP1989 commented on open-api/typescript-client/apis.mustache
This was some copypaste bloating, removed it.

2024-02-19 11:42 UTC, lauriLukkarinen approved these changes

2024-02-19 11:43 UTC, lauriLukkarinen approved these changes

2024-02-19 11:44 UTC, merged