Feature 25 routes tasks drag and drop
Metatavu/vp-kuljetus-transport-management pull request #59
Opened 2024-05-30 16:34 UTC by villejuutila

Resolves #25

2024-06-03 10:30 UTC, lauriLukkarinen requested changes

2024-06-03 10:30 UTC, lauriLukkarinen commented on src/components/drive-planning/routes/unallocated-tasks-table.tsx
> +  const getDistinctFreights = () => [...new Set((tasksQuery.data?.tasks ?? []).map((task) => task.freightId))];
This only compares object references, so it does not actually get distinct tasks, as they will have different refs when parsed from the API response.

2024-06-03 10:30 UTC, lauriLukkarinen commented on src/components/drive-planning/routes/unallocated-tasks-table.tsx
> +  const columns: GridColDef[] = useMemo(
Add row model type here
`GridColDef<T>[]`
to get proper types in renderCell functions

2024-06-03 10:30 UTC, lauriLukkarinen commented on src/routes/drive-planning.routes.tsx
> +  const localTasksBeforeDrag = useRef<null | TRouteTasks>(null);
```suggestion
  const localTasksBeforeDrag = useRef<TRouteTasks | null>(null);
```

2024-06-03 10:30 UTC, lauriLukkarinen commented on src/routes/drive-planning.routes.tsx
> +      toast.success("Tehtävän siirto onnistui!");
Localize

2024-06-03 10:30 UTC, lauriLukkarinen commented on src/types/index.ts
> +
```suggestion
```

2024-06-03 10:46 UTC, villejuutila commented on src/components/drive-planning/routes/draggable-routes-tasks-table-row.tsx
> +  const style: React.CSSProperties = useMemo(
Resolved

2024-06-03 10:47 UTC, villejuutila commented on src/components/drive-planning/routes/draggable-unallocated-tasks-table-row.tsx
> +}) => {
Resolved

2024-06-03 10:47 UTC, villejuutila commented on src/components/drive-planning/routes/expandable-routes-table-row.tsx
> +  );
Resolved

2024-06-03 10:49 UTC, villejuutila commented on src/components/drive-planning/routes/draggable-unallocated-tasks-table-row.tsx
> +          onClick={() => navigate({ search: { freightId: params.row?.freightId, date: undefined } })}
Resolved

2024-06-03 10:50 UTC, villejuutila commented on src/components/drive-planning/routes/routes-table.tsx
> +    if (!row.id) return;
Resolved

2024-06-03 10:51 UTC, villejuutila commented on src/components/drive-planning/routes/routes-tasks-table-row.tsx
> +    const [menuCoordinates, setMenuCoordinates] = useState<{ clientX: number; clientY: number } | undefined>();
Resolved

2024-06-03 10:52 UTC, villejuutila commented on src/components/drive-planning/routes/routes-tasks-table-row.tsx
> +            onClick={() => navigate({ search: { freightId: foundFreight.id, date: undefined } })}
Resolved

2024-06-03 10:53 UTC, villejuutila commented on src/components/drive-planning/routes/unallocated-tasks-table.tsx
> +  const columns: GridColDef[] = useMemo(
Resolved

2024-06-03 10:54 UTC, villejuutila commented on src/routes/drive-planning.routes.tsx
> +  const localTasksBeforeDrag = useRef<null | TRouteTasks>(null);
Resolved

2024-06-03 10:55 UTC, villejuutila commented on src/routes/drive-planning.routes.tsx
> +      toast.success("Tehtävän siirto onnistui!");
Resolved

2024-06-03 10:55 UTC, villejuutila commented on src/types/index.ts
> +
Resolved

2024-06-05 06:22 UTC, lauriLukkarinen approved these changes

2024-06-05 06:23 UTC, lauriLukkarinen approved these changes

2024-06-05 06:24 UTC, merged