Added logic to create separate rows when tasks are done during drive …
Metatavu/vp-kuljetus-transport-management pull request #64
Opened 2024-05-31 14:50 UTC by EVP1989

Resolves #55

2024-06-03 09:36 UTC, lauriLukkarinen requested changes

2024-06-03 09:36 UTC, lauriLukkarinen commented on src/localization/locales/fi.json
> +    },
Should this have the "working" also?

2024-06-03 09:36 UTC, lauriLukkarinen commented on src/routes/vehicle-list_.vehicles.$vehicleId.info.tsx
> +  });
```suggestion
  const routesQueryParams = {
    truckId: vehicleId,
    departureAfter: selectedDate?.startOf("day").toJSDate(),
    departureBefore: selectedDate?.endOf("day").toJSDate(),
  };
  const routes = useQuery({
    queryKey: ["routes", routesQueryParams],
    queryFn: async () => await routesApi.listRoutes(routesQueryParams),
  });
```

2024-06-03 09:36 UTC, lauriLukkarinen commented on src/routes/vehicle-list_.vehicles.$vehicleId.info.tsx
>    });
No suggestion because of deleted lines, but this could be like this:

```
  const driveStatesQueryParams = {
    truckId: vehicleId,
    after: selectedDate?.startOf("day").toJSDate(),
    before: selectedDate?.endOf("day").toJSDate(),
  };
  const driveStates = useQuery({
    queryKey: ["driveStates", driveStatesQueryParams],
    queryFn: () => trucksApi.listDriveStates(driveStatesQueryParams),
    select: (data) => data.sort((a, b) => a.timestamp - b.timestamp),
  });
```

2024-06-03 09:36 UTC, lauriLukkarinen commented on src/routes/vehicle-list_.vehicles.$vehicleId.info.tsx
> +    const tableRows = driveStates.data.reduce<DriveStatesTableRow[]>((rows, driveState, index, driveStates) => {
This should be sliced to smaller functions that explain the context and logical steps better.

2024-06-03 09:36 UTC, lauriLukkarinen commented on src/utils/localization-utils.ts
> +    WORK: t("vehicleList.truckDriveStateStatus.stopped"),
This should be "working"

2024-06-04 04:33 UTC, EVP1989 commented on src/localization/locales/fi.json
> +    },
Did not see that in the design, but will add and can be removed later. Makes sense to have it there.

2024-06-05 06:32 UTC, lauriLukkarinen requested changes

2024-06-05 07:53 UTC, lauriLukkarinen approved these changes

2024-06-05 07:53 UTC, merged