Added functionality for getting working periods for drivers and offic…
Metatavu/vp-kuljetus-transport-management pull request #86
Opened 2024-08-08 17:03 UTC by EVP1989

Resolves #85

2024-08-14 07:48 UTC, lauriLukkarinen requested changes

2024-08-14 07:48 UTC, lauriLukkarinen commented on src/hooks/use-queries.ts
> +  console.log("WORKING PERIOD DATES", getWorkingPeriodDates(SalaryGroup.Office, DateTime.now().set({month: 3, day: 17}).toJSDate()));
```suggestion
```

2024-08-14 07:48 UTC, lauriLukkarinen commented on src/hooks/use-queries.ts
> +  if (!salaryGroup) {
This should not happen as the parameter is not typed optional. If it still happens, the reason should be solved, or if it doesn't, this condition can be removed.

2024-08-14 07:48 UTC, lauriLukkarinen commented on src/hooks/use-queries.ts
> +    return getNonOfficePeriod(selectedDateTime);
```suggestion
  return isOfficeOrTerminalGroup(salaryGroup) 
    ? getOfficeOrTerminalPeriod(selectedDateTime)
    : getNonOfficePeriod(selectedDateTime);
  }
```

2024-08-14 07:48 UTC, lauriLukkarinen commented on src/hooks/use-queries.ts
> +    return { start, end };
```suggestion
  }

  const start = selectedDateTime.set({ day: 16 }).startOf("day").toJSDate();
  const end = selectedDateTime.endOf("month").endOf("day").toJSDate();
  return { start, end };
```

2024-08-14 07:48 UTC, lauriLukkarinen commented on src/hooks/use-queries.ts
> +const getNonOfficePeriod = (selectedDateTime: DateTime) => {
This could be named getDriverPeriod, as the other option apart from office and terminal employee is only driver.

2024-08-14 07:48 UTC, lauriLukkarinen commented on src/hooks/use-queries.ts
> +    return calculatePeriod(fullWeeksFromStartDate - 1);
This can be shortened like this, as the remainder is always 0 or 1 when dividing a number by 2 (if rounded up, otherwise 1 week would be wrong).

```suggestion
  const remainderRoundedUp = Math.ceil(fullWeeksFromStartDate % 2);
  return calculatePeriod(fullWeeksFromStartDate - remainderRoundedUp);
```

2024-08-14 07:48 UTC, lauriLukkarinen commented on src/routes/management.employees_.$employeeId.modify.tsx
> +  console.log("employeeQuery", JSON.stringify(employeeQuery.data, null, 2));
```suggestion
```

2024-08-14 07:48 UTC, lauriLukkarinen commented on src/routes/management.employees_.$employeeId.modify.tsx
> +    end: DateTime.now().toJSDate(), */,
Why is this comment here?

2024-08-14 07:48 UTC, lauriLukkarinen commented on src/routes/management.employees_.$employeeId.modify.tsx
> +  console.log("timeEntryQuery", JSON.stringify(timeEntryQuery.data, null, 2));
```suggestion
```

2024-08-15 12:45 UTC, EVP1989 commented on src/routes/management.employees_.$employeeId.modify.tsx
> +  console.log("timeEntryQuery", JSON.stringify(timeEntryQuery.data, null, 2));
Removed this.

2024-08-15 12:45 UTC, EVP1989 commented on src/routes/management.employees_.$employeeId.modify.tsx
> +    end: DateTime.now().toJSDate(), */,
Removed.

2024-08-15 12:46 UTC, EVP1989 commented on src/routes/management.employees_.$employeeId.modify.tsx
> +  console.log("employeeQuery", JSON.stringify(employeeQuery.data, null, 2));
Removed after testing.

2024-08-15 12:46 UTC, EVP1989 commented on src/hooks/use-queries.ts
> +const getNonOfficePeriod = (selectedDateTime: DateTime) => {
Renamed.

2024-08-15 12:47 UTC, EVP1989 commented on src/hooks/use-queries.ts
> +  if (!salaryGroup) {
Changed logic to include also "selectedDate" and "useWorkingPeriod" boolean for using the same method for getting all time entries if needed.

2024-08-15 12:47 UTC, EVP1989 commented on src/hooks/use-queries.ts
> +  console.log("WORKING PERIOD DATES", getWorkingPeriodDates(SalaryGroup.Office, DateTime.now().set({month: 3, day: 17}).toJSDate()));
Removed this.

2024-08-20 07:03 UTC, lauriLukkarinen approved these changes

2024-08-20 07:03 UTC, lauriLukkarinen commented on src/routes/management.employees_.$employeeId.modify.tsx
> +    DateTime.now().set({ month: 3, day: 11 }).toJSDate(),
```suggestion
    Date.now(),
```

2024-08-20 07:25 UTC, lauriLukkarinen approved these changes

2024-08-20 07:26 UTC, merged